### ISSUE TITLE
typo in tickets. Feb 17th

### ISSUE THREAD

**Issue by josmas** [belfastkats/belfastkats.github.io#5]
Hey there; not sure who has access to this repo. The [tickets section reads Sat 17th September 2016](https://github.com/belfastkats/belfastkats.github.io/blob/master/index.html#L370) and needs to be corrected to 18th Feb 2017. Opening a PR is more trouble than worth.

**Comment by belfastfp** [comment]
Fixed way back in Oct 2016. Closing.
